import {Models} from "../types/types.ts";

export const models:  Models = {
  'shoes': {
    modelName: 'Adidas Sneakers',
    modelUrl: '/models/Adidas_Stan_Smith.glb',
    modelPosition: [0, -0.2, 0],
    modelRotation: [0.2, 0, 0],
    lightMode: 'mode-1',
    categories: [
      {
        openedByDefault: true,
        categoryName: 'Main',
        materialType: 'MESHSTANDARDMATERIAL',
        decals: [],
        materialNames: ['Circle021_1', 'Circle024_1'],
        subCategories: [
          {
            title: 'Material',
            options: [
              {
                id: 'cbf6c9ff-66c6-4b4d-bf15-3a6fa1bfcf6d',
                isActive: false,
                isColorPreview: false,
                color: '',
                preview: '/materials/leather/lather.webp',
                title: 'leather',
                setting: {
                  // roughness: "0.5",
                  normalMap: "/materials/leather/leather_Normal_flip.jpg",
                  roughnessMap: "/materials/leather/leather_Roughness_flip.jpg",
                }
              },
              {
                id: '23fdad76-2f8f-4058-aabc-4482bdb1125c',
                isActive: false,
                isColorPreview: false,
                color: '',
                preview: '/materials/fabric/fabric_1.jpeg',
                title: 'Fabric',
                setting: {
                  roughness: 0.65,
                  normalMap: "/materials/fabric/fabric_Normal_flip.jpg",
                  roughnessMap: "/materials/fabric/fabric_Roughness_flip.jpg",
                  normalScaleX: -2,
                  normalScaleY: -1,
                }
              },
            ]
          },
          {
            title: 'Color',
            options: [
              {
                id: 'b7fa45f1-914e-41c1-87fc-542b716aa97c',
                isActive: false,
                isColorPreview: true,
                color: '#FFFFFF',
                preview: '',
                title: '',
              },
              {
                id: 'b2f94388-d4e3-4e09-bb5d-86d26d162d98',
                isActive: false,
                isColorPreview: true,
                color: '#151515',
                preview: '',
                title: '',
              },
              {
                id: 'b59c3e54-81d6-4d26-a7d4-1b40d489d179',
                isActive: false,
                isColorPreview: true,
                color: '#8B88FD',
                preview: '',
                title: '',
              },
              {
                id: '6ae2b59b-94f1-4a90-9a71-0cb96dfab7ef',
                isActive: false,
                isColorPreview: true,
                color: '#B8EB63',
                preview: '',
                title: '',
              },
              {
                id: '4d8c98e1-fcfd-4c2f-9c84-8c31de2a3f5a',
                isActive: false,
                isColorPreview: true,
                color: '#63DBEB',
                preview: '',
                title: '',
              },
              {
                id: 'a12b45d4-53d5-4f65-9c39-9b76d0f8c0e2',
                isActive: false,
                isColorPreview: true,
                color: '#EB6363',
                preview: '',
                title: '',
              },
              {
                id: 'e1a7c6b4-2e6e-4f02-b5e3-c5a2b94d5a09',
                isActive: false,
                isColorPreview: true,
                color: '#EBBD63',
                preview: '',
                title: '',
              },
              {
                id: 'bc5e9ae1-f9c5-48d0-8281-8e5694d4ed87',
                isActive: false,
                isColorPreview: true,
                color: '#003366',
                preview: '',
                title: '',
              },
              {
                id: '46e5b04a-3e9a-4b61-8b75-7a7f510dce80',
                isActive: false,
                isColorPreview: true,
                color: '#808080',
                preview: '',
                title: '',
              },
              {
                id: 'a9e2b2b0-e6e2-4b47-9439-e6a6c3e8d63d',
                isActive: false,
                isColorPreview: true,
                color: '#F5F5DC',
                preview: '',
                title: '',
              },
              {
                id: '9fce1a90-c8ed-41c5-9738-fab6e1d68c5c',
                isActive: false,
                isColorPreview: true,
                color: '#D5B9A0',
                preview: '',
                title: '',
              },
              {
                id: '8e5a5c1b-3d46-40b3-91b7-973bfa549aa1',
                isActive: false,
                isColorPreview: true,
                color: '#6B8E23',
                preview: '',
                title: '',
              },
              {
                id: '7ae0b1b2-7c68-47c2-b1b7-4f3796b8f060',
                isActive: false,
                isColorPreview: true,
                color: '#800000',
                preview: '',
                title: '',
              },
              {
                id: 'd6fd5f40-36a3-4973-bc04-cb4d07b238f1',
                isActive: false,
                isColorPreview: true,
                color: '#87CEEB',
                preview: '',
                title: '',
              },
              {
                id: 'e2b5824d-bc47-4b86-8e8a-d123bc0652eb',
                isActive: false,
                isColorPreview: true,
                color: '#FFC0CB',
                preview: '',
                title: '',
              },
              {
                id: '0c0d0a63-c5f7-4342-8d9b-0ed5f5879f34',
                isActive: false,
                isColorPreview: true,
                color: '#2F4F4F',
                preview: '',
                title: '',
              },
              {
                id: 'b0e6d6f0-63d0-4a29-8d3a-d8a56c104c85',
                isActive: false,
                isColorPreview: true,
                color: '#E2725B',
                preview: '',
                title: '',
              },
              {
                id: 'ad0bfa77-1a6b-490f-b3d3-79f7e747d59c',
                isActive: false,
                isColorPreview: true,
                color: '#98FF98',
                preview: '',
                title: '',
              },
              {
                id: 'd7b6a6d5-d2b7-40e4-9b36-09b7e9c7b044',
                isActive: false,
                isColorPreview: true,
                color: '#00FFFF',
                preview: '',
                title: '',
              },
              {
                id: 'a6a25c9c-21c0-4a06-91c0-9359d048cb42',
                isActive: false,
                isColorPreview: true,
                color: '#F4A460',
                preview: '',
                title: '',
              },
              {
                id: 'a9d5f87c-50cb-4f27-8e86-cd1c88b7a2eb',
                isActive: false,
                isColorPreview: true,
                color: '#4B2E2A',
                preview: '',
                title: '',
              },
              {
                id: 'c35a629a-6508-418c-b3e2-86e5e768845e',
                isActive: false,
                isColorPreview: true,
                color: '#800080',
                preview: '',
                title: '',
              },
              {
                id: 'b7f9796f-8d67-4c7a-bd7b-0c82a85b8ac6',
                isActive: false,
                isColorPreview: true,
                color: '#006400',
                preview: '',
                title: '',
              },
              {
                id: '6a74322d-d6eb-4b2d-b6c4-3e3e9e9e1b73',
                isActive: false,
                isColorPreview: true,
                color: '#E0115F',
                preview: '',
                title: '',
              },
            ]
          }
        ]
      },
      {
        openedByDefault: false,
        categoryName: 'Back',
        materialType: 'MESHSTANDARDMATERIAL',
        materialNames: ['Circle021_2', 'Circle024_2'],
        decals: ['Circle033_1', 'Circle036_1'],
        subCategories: [
          {
            title: 'Material',
            options: [
              {
                id: 'f2f4a0c1-00e1-4524-85e4-f1c9ea0c31fc',
                isActive: false,
                isColorPreview: false,
                color: '',
                preview: '/materials/leather/lather.png',
                title: 'leather',
                setting: {
                  // roughness: "0.5",
                  normalMap: "/materials/leather/leather_Normal_flip.jpg",
                  roughnessMap: "/materials/leather/leather_Roughness_flip.jpg",
                }
              },
              {
                id: 'de4edc6f-e3c7-4d5f-8d88-5065cf764f4d',
                isActive: false,
                isColorPreview: false,
                color: '',
                preview: '/materials/fabric/fabric_1.png',
                title: 'Fabric',
                setting: {
                  roughness: 0.65,
                  normalMap: "/materials/fabric/fabric_Normal_flip.jpg",
                  roughnessMap: "/materials/fabric/fabric_Roughness_flip.jpg",
                }
              },
            ]
          },
          {
            title: 'Color',
            options: [
              {
                id: 'f7b4527e-59c6-46db-a9b3-826c7d2b7a5b',
                isActive: false,
                isColorPreview: true,
                color: '#FFFFFF',
                preview: '',
                title: '',
              },
              {
                id: '7d7e246b-f372-4e4f-8cb7-fd79f78f5e44',
                isActive: false,
                isColorPreview: true,
                color: '#151515',
                preview: '',
                title: '',
              },
              {
                id: '54d1e4cf-48c6-442a-bc07-178d55db6d58',
                isActive: false,
                isColorPreview: true,
                color: '#8B88FD',
                preview: '',
                title: '',
              },
              {
                id: '7c6f7e6a-4a9b-4c7d-9f4a-92b0328fa382',
                isActive: false,
                isColorPreview: true,
                color: '#B8EB63',
                preview: '',
                title: '',
              },
              {
                id: 'd4ed7f4b-8c43-4c96-bb8a-095d473fb3b3',
                isActive: false,
                isColorPreview: true,
                color: '#63DBEB',
                preview: '',
                title: '',
              },
              {
                id: '8f7b8d9c-b6e5-4f9d-979f-6b6b8c5df87e',
                isActive: false,
                isColorPreview: true,
                color: '#EB6363',
                preview: '',
                title: '',
              },
              {
                id: 'e7c8b0a5-c3eb-4b48-a7d4-5b83d11dbd87',
                isActive: false,
                isColorPreview: true,
                color: '#EBBD63',
                preview: '',
                title: '',
              },
              {
                id: 'b42e4b99-740c-4dfc-bb48-6d8c9e2e86b7',
                isActive: false,
                isColorPreview: true,
                color: '#003366',
                preview: '',
                title: '',
              },
              {
                id: '1f3b9f2b-5db5-4d85-9eeb-6e3f2c167b9a',
                isActive: false,
                isColorPreview: true,
                color: '#808080',
                preview: '',
                title: '',
              },
              {
                id: 'f372f8c4-852b-4c72-8e1d-b8f3e48a4c9e',
                isActive: false,
                isColorPreview: true,
                color: '#F5F5DC',
                preview: '',
                title: '',
              },
              {
                id: 'ab9d5e4a-2b08-4372-9147-c5f48de54a1f',
                isActive: false,
                isColorPreview: true,
                color: '#D5B9A0',
                preview: '',
                title: '',
              },
              {
                id: 'd469f8d8-bd67-429e-b91d-1db9c4e40e1e',
                isActive: false,
                isColorPreview: true,
                color: '#6B8E23',
                preview: '',
                title: '',
              },
              {
                id: '78b2d6a2-00ef-4d68-944a-6d23f962e3d7',
                isActive: false,
                isColorPreview: true,
                color: '#800000',
                preview: '',
                title: '',
              },
              {
                id: 'eaf03539-1d7a-4f2e-8d4f-5e6b34c2d6d5',
                isActive: false,
                isColorPreview: true,
                color: '#87CEEB',
                preview: '',
                title: '',
              },
              {
                id: '7dcae572-2b6e-4938-9f9b-b74236d04616',
                isActive: false,
                isColorPreview: true,
                color: '#FFC0CB',
                preview: '',
                title: '',
              },
              {
                id: 'a4cb64f6-07b2-4f94-b8c8-4a38b6dbf4cb',
                isActive: false,
                isColorPreview: true,
                color: '#2F4F4F',
                preview: '',
                title: '',
              },
              {
                id: '5b29f86e-b1bc-46cf-9752-0b4f3e6a12b1',
                isActive: false,
                isColorPreview: true,
                color: '#E2725B',
                preview: '',
                title: '',
              },
              {
                id: 'c83c8c71-5f46-4b47-84fb-eaf04ac1f6cf',
                isActive: false,
                isColorPreview: true,
                color: '#98FF98',
                preview: '',
                title: '',
              },
              {
                id: 'f4a2b178-c62a-4736-9dc4-cf78696c86a8',
                isActive: false,
                isColorPreview: true,
                color: '#00FFFF',
                preview: '',
                title: '',
              },
              {
                id: '71a2a9b2-d2e6-45d2-bb15-8c11cdb72d74',
                isActive: false,
                isColorPreview: true,
                color: '#F4A460',
                preview: '',
                title: '',
              },
              {
                id: '87b8e1b2-d8d4-4f96-bd3e-d28dffb22b91',
                isActive: false,
                isColorPreview: true,
                color: '#4B2E2A',
                preview: '',
                title: '',
              },
              {
                id: 'c4b6f4c1-b94f-4326-9b67-473a46b9f693',
                isActive: false,
                isColorPreview: true,
                color: '#800080',
                preview: '',
                title: '',
              },
              {
                id: 'a6f423c7-8d38-4e7d-a2d2-2b7b36787d6d',
                isActive: false,
                isColorPreview: true,
                color: '#006400',
                preview: '',
                title: '',
              },
              {
                id: '09c8e8f3-c53f-4b9f-bce5-cd90d3c5b5eb',
                isActive: false,
                isColorPreview: true,
                color: '#E0115F',
                preview: '',
                title: '',
              },
            ]
          }
        ]
      },
      {
        openedByDefault: false,
        categoryName: 'Sole',
        materialType: 'MESHSTANDARDMATERIAL',
        materialNames: ['Circle021_3', 'Circle024_3'],
        decals: [],
        subCategories: [
          // {
          //   title: 'Material',
          //   options: [
          //     {
          //       id: 'd1ec55f4-24ed-4c44-8d7f-1f6de2f51680',
          //       isActive: false,
          //       isColorPreview: false,
          //       color: '',
          //       preview: '/materials/leather/lather.png',
          //       title: 'leather',
          //       setting: {
          //         // roughness: "0.5",
          //         normalMap: "/materials/leather/leather_Normal_flip.jpg",
          //         roughnessMap: "/materials/leather/leather_Roughness_flip.jpg",
          //       }
          //     },
          //     {
          //       id: 'b87c6e6e-e60e-4dc1-a2c2-1a52f67bb8c3',
          //       isActive: false,
          //       isColorPreview: false,
          //       color: '',
          //       preview: '/materials/fabric/fabric_1.png',
          //       title: 'Fabric',
          //       setting: {
          //         roughness: 0.65,
          //         normalMap: "/materials/fabric/fabric_Normal_flip.jpg",
          //         roughnessMap: "/materials/fabric/fabric_Roughness_flip.jpg",
          //       }
          //     },
          //   ]
          // },
          {
            title: 'Color',
            options: [
              {
                id: 'a7b295f4-0d5e-42a8-a8b6-708d3baf2579',
                isActive: false,
                isColorPreview: true,
                color: '#FFFFFF',
                preview: '',
                title: '',
              },
              {
                id: 'fd5b4c91-10c2-4e16-8e0d-0d5466c8b7f1',
                isActive: false,
                isColorPreview: true,
                color: '#151515',
                preview: '',
                title: '',
              },
              {
                id: 'a2bc8f2f-e66d-4c2e-8b80-dc65d6f7b817',
                isActive: false,
                isColorPreview: true,
                color: '#8B88FD',
                preview: '',
                title: '',
              },
              {
                id: 'f29d9f9b-0300-45e2-b6b2-f388b9b52a23',
                isActive: false,
                isColorPreview: true,
                color: '#B8EB63',
                preview: '',
                title: '',
              },
              {
                id: 'b8a0d0f2-0f6b-493a-8bba-6a5d1f14c8b9',
                isActive: false,
                isColorPreview: true,
                color: '#63DBEB',
                preview: '',
                title: '',
              },
              {
                id: '2b52f1cb-22b3-4a45-88b8-18a283f4e2a4',
                isActive: false,
                isColorPreview: true,
                color: '#EB6363',
                preview: '',
                title: '',
              },
              {
                id: 'd5e9a1e5-70db-4b6d-93d7-c7d7b5dc8eb2',
                isActive: false,
                isColorPreview: true,
                color: '#EBBD63',
                preview: '',
                title: '',
              },
              {
                id: 'ce8f8c8f-58d1-4b38-85ae-9f9c6b9e0747',
                isActive: false,
                isColorPreview: true,
                color: '#003366',
                preview: '',
                title: '',
              },
              {
                id: 'e7b91a7b-df73-4e65-9d63-d6d88f7b732e',
                isActive: false,
                isColorPreview: true,
                color: '#808080',
                preview: '',
                title: '',
              },
              {
                id: '4c31b674-0b6c-4c6f-a0a4-1f13d9d2fc53',
                isActive: false,
                isColorPreview: true,
                color: '#F5F5DC',
                preview: '',
                title: '',
              },
              {
                id: '13d4f1e0-069f-437c-b51b-72a36e7d8e8c',
                isActive: false,
                isColorPreview: true,
                color: '#D5B9A0',
                preview: '',
                title: '',
              },
              {
                id: '65a223ab-c77b-4c0e-87b6-df95c8e8e10b',
                isActive: false,
                isColorPreview: true,
                color: '#6B8E23',
                preview: '',
                title: '',
              },
              {
                id: 'ecae37d7-8c4e-42a5-9bfc-d95c4d9c74ae',
                isActive: false,
                isColorPreview: true,
                color: '#800000',
                preview: '',
                title: '',
              },
              {
                id: 'bcd4a1b2-e28a-4740-b5ea-d00ebf1c7a8d',
                isActive: false,
                isColorPreview: true,
                color: '#87CEEB',
                preview: '',
                title: '',
              },
              {
                id: 'f0f4c08e-4ec2-41e1-91a8-35b2ea4d3a6b',
                isActive: false,
                isColorPreview: true,
                color: '#FFC0CB',
                preview: '',
                title: '',
              },
              {
                id: '17c84d68-fb58-41bb-9413-08ff35b8e4c2',
                isActive: false,
                isColorPreview: true,
                color: '#2F4F4F',
                preview: '',
                title: '',
              },
              {
                id: 'a2b848cc-4dbe-4877-8b8e-06d12e14c4d6',
                isActive: false,
                isColorPreview: true,
                color: '#E2725B',
                preview: '',
                title: '',
              },
              {
                id: 'fbda7e6e-84e4-4f5b-b5b8-c2b7bb9efad1',
                isActive: false,
                isColorPreview: true,
                color: '#98FF98',
                preview: '',
                title: '',
              },
              {
                id: '4d78b11e-cb0b-4c8c-a9a8-b845f0e9b587',
                isActive: false,
                isColorPreview: true,
                color: '#00FFFF',
                preview: '',
                title: '',
              },
              {
                id: '9cf29e9e-4b23-45b5-85d7-79fd2f3c2827',
                isActive: false,
                isColorPreview: true,
                color: '#F4A460',
                preview: '',
                title: '',
              },
              {
                id: '5a24c3b6-8c7b-4a04-bd7c-3a7f12a4e7a1',
                isActive: false,
                isColorPreview: true,
                color: '#4B2E2A',
                preview: '',
                title: '',
              },
              {
                id: 'd2d2b46b-623d-4e72-8b5b-b1c6bb4cfb93',
                isActive: false,
                isColorPreview: true,
                color: '#800080',
                preview: '',
                title: '',
              },
              {
                id: '3e58630c-fb90-4f0e-bf7e-f14d4f5f7d32',
                isActive: false,
                isColorPreview: true,
                color: '#006400',
                preview: '',
                title: '',
              },
              {
                id: '1a6a9d73-82f3-4e4a-90e6-47d2a6211e3a',
                isActive: false,
                isColorPreview: true,
                color: '#E0115F',
                preview: '',
                title: '',
              },
            ]
          }
        ]
      },
      {
        openedByDefault: false,
        categoryName: 'Laces',
        materialType: 'MESHSTANDARDMATERIAL',
        decals: [],
        materialNames: ['Circle021_4', 'Circle024_4'],
        subCategories: [
          // {
          //   title: 'Material',
          //   options: [
          //     {
          //       id: 'f128c231-aceb-4f61-a95e-c2147a33d5c2',
          //       isActive: false,
          //       isColorPreview: false,
          //       color: '',
          //       preview: '/materials/lather.png',
          //       title: 'leather',
          //     },
          //     {
          //       id: '2f647f85-356e-4295-8ed5-16c28f9e15cf',
          //       isActive: false,
          //       isColorPreview: false,
          //       color: '',
          //       preview: '/materials/fabric_1.png',
          //       title: 'Fabric',
          //     },
          //   ]
          // },
          {
            title: 'Color',
            options: [
              {
                id: 'e8b12b26-1e48-4c94-9a66-02f80937c5e2',
                isActive: false,
                isColorPreview: true,
                color: '#FFFFFF',
                preview: '',
                title: '',
              },
              {
                id: '34b1c688-bd09-4a92-930c-5cfb77c0555f',
                isActive: false,
                isColorPreview: true,
                color: '#151515',
                preview: '',
                title: '',
              },
              {
                id: '7e3b71a2-4030-4a6b-9d5e-dfc8d73ad4a4',
                isActive: false,
                isColorPreview: true,
                color: '#8B88FD',
                preview: '',
                title: '',
              },
              {
                id: '3d82dcb3-15b2-4d7e-9c94-845a2a6d54f4',
                isActive: false,
                isColorPreview: true,
                color: '#B8EB63',
                preview: '',
                title: '',
              },
              {
                id: '7d346f6d-8b35-47d7-9d62-5f4e61c5e58a',
                isActive: false,
                isColorPreview: true,
                color: '#63DBEB',
                preview: '',
                title: '',
              },
              {
                id: '1cb0036e-8f29-4d3d-a1f2-4e4d18442fdc',
                isActive: false,
                isColorPreview: true,
                color: '#EB6363',
                preview: '',
                title: '',
              },
              {
                id: 'b5a2b2c7-847c-4e4f-b3c3-0303b557b2d4',
                isActive: false,
                isColorPreview: true,
                color: '#EBBD63',
                preview: '',
                title: '',
              },
              {
                id: 'c4d8968c-df0d-4fa3-8973-3a84f8bfe6d0',
                isActive: false,
                isColorPreview: true,
                color: '#003366',
                preview: '',
                title: '',
              },
              {
                id: '8d5b5b53-cf37-4f76-bb5e-258b3d4d8b7d',
                isActive: false,
                isColorPreview: true,
                color: '#808080',
                preview: '',
                title: '',
              },
              {
                id: 'c2b8d2e6-0f4d-4b60-bd8b-5db062cf591e',
                isActive: false,
                isColorPreview: true,
                color: '#F5F5DC',
                preview: '',
                title: '',
              },
              {
                id: '5e41dbb8-8329-4b1b-8a8d-8e6c2b8e43d5',
                isActive: false,
                isColorPreview: true,
                color: '#D5B9A0',
                preview: '',
                title: '',
              },
              {
                id: '98fbe0d1-7e1d-4b56-85d2-6c50b840c5d8',
                isActive: false,
                isColorPreview: true,
                color: '#6B8E23',
                preview: '',
                title: '',
              },
              {
                id: 'a97bfa35-62d7-4f7a-a5b1-0b6c9c4b7e7a',
                isActive: false,
                isColorPreview: true,
                color: '#800000',
                preview: '',
                title: '',
              },
              {
                id: '7fb3c5b0-4d37-4c67-99a2-30ea056bd2b2',
                isActive: false,
                isColorPreview: true,
                color: '#87CEEB',
                preview: '',
                title: '',
              },
              {
                id: '8d8b702f-4c84-47a5-9787-302c78b0a04f',
                isActive: false,
                isColorPreview: true,
                color: '#FFC0CB',
                preview: '',
                title: '',
              },
              {
                id: 'ad89b03c-3bbf-4d96-9252-0cbaed5c1a32',
                isActive: false,
                isColorPreview: true,
                color: '#2F4F4F',
                preview: '',
                title: '',
              },
              {
                id: 'e7c2d6b3-89f6-4b1b-9e8f-39b6cf13b59b',
                isActive: false,
                isColorPreview: true,
                color: '#E2725B',
                preview: '',
                title: '',
              },
              {
                id: '1b5b83f7-8e1d-4b78-b4c1-9e8a7c4e3a12',
                isActive: false,
                isColorPreview: true,
                color: '#98FF98',
                preview: '',
                title: '',
              },
              {
                id: '4a0c68f1-3b62-4e8e-952e-bb05f6b0b697',
                isActive: false,
                isColorPreview: true,
                color: '#00FFFF',
                preview: '',
                title: '',
              },
              {
                id: 'ea8b4b15-0b5b-45eb-86d0-f2e945d09e9d',
                isActive: false,
                isColorPreview: true,
                color: '#F4A460',
                preview: '',
                title: '',
              },
              {
                id: 'a67b6d32-78c3-4c6b-bf87-1e1a9b8b4f4e',
                isActive: false,
                isColorPreview: true,
                color: '#4B2E2A',
                preview: '',
                title: '',
              },
              {
                id: 'ef8b5c45-1b29-45a8-a4d2-7e535a635ad1',
                isActive: false,
                isColorPreview: true,
                color: '#800080',
                preview: '',
                title: '',
              },
              {
                id: 'd6a8b9c5-0a6b-4b28-91a3-d8b7c2e24e3f',
                isActive: false,
                isColorPreview: true,
                color: '#006400',
                preview: '',
                title: '',
              },
              {
                id: 'b519f5f3-07c1-4a3f-aac8-f27e8c9d1e7e',
                isActive: false,
                isColorPreview: true,
                color: '#E0115F',
                preview: '',
                title: '',
              },
            ]
          }
        ]
      },
      {
        openedByDefault: false,
        categoryName: 'Holes',
        materialType: 'MESHSTANDARDMATERIAL',
        decals: [],
        materialNames: ['Circle021_5', 'Circle024_5'],
        subCategories: [
          // {
          //   title: 'Material',
          //   options: [
          //     {
          //       id: '637e1f34-25d4-4d48-8482-e73e65e3d755',
          //       isActive: false,
          //       isColorPreview: false,
          //       color: '',
          //       preview: '/materials/lather.png',
          //       title: 'leather',
          //     },
          //     {
          //       id: '2a57c0f7-3d0e-4c01-8b38-c4532f9d93ef',
          //       isActive: false,
          //       isColorPreview: false,
          //       color: '',
          //       preview: '/materials/fabric_1.png',
          //       title: 'Fabric',
          //     },
          //   ]
          // },
          {
            title: 'Color',
            options: [
              {
                id: '5c372634-36e2-4e8a-bc8b-1cfd58a8c46e',
                isActive: false,
                isColorPreview: true,
                color: '#FFFFFF',
                preview: '',
                title: '',
              },
              {
                id: 'a3e7df86-5e35-4041-8394-f05703051e9f',
                isActive: false,
                isColorPreview: true,
                color: '#151515',
                preview: '',
                title: '',
              },
            ]
          }
        ]
      },
      {
        openedByDefault: false,
        categoryName: 'Slipsole',
        materialType: 'MESHSTANDARDMATERIAL',
        decals: [],
        materialNames: ['Circle021_6', 'Circle024_6'],
        subCategories: [
          {
            title: 'Material',
            options: [
              {
                id: '6743d1ad-686a-405e-9dd6-5cb601a47299',
                isActive: false,
                isColorPreview: false,
                color: '',
                preview: '/materials/leather/lather.png',
                title: 'leather',
                setting: {
                  // roughness: "0.5",
                  normalMap: "/materials/leather/leather_Normal_flip.jpg",
                  roughnessMap: "/materials/leather/leather_Roughness_flip.jpg",
                }
              },
              {
                id: '00709d9c-7fcb-45a0-bba2-659ccf2f8b0c',
                isActive: false,
                isColorPreview: false,
                color: '',
                preview: '/materials/fabric/fabric_1.png',
                title: 'Fabric',
                setting: {
                  roughness: 0.65,
                  normalMap: "/materials/fabric/fabric_Normal_flip.jpg",
                  roughnessMap: "/materials/fabric/fabric_Roughness_flip.jpg",
                }
              },
            ]
          },
          {
            title: 'Color',
            options: [
              {
                id: '7a3f1c43-9b37-4b47-b636-bf5c05f84c2e',
                isActive: false,
                isColorPreview: true,
                color: '#FFFFFF',
                preview: '',
                title: '',
              },
              {
                id: 'a4a45e6b-5e44-42b5-b8b6-56e88b233e6f',
                isActive: false,
                isColorPreview: true,
                color: '#151515',
                preview: '',
                title: '',
              },
              {
                id: 'b2e84d2e-d1fc-4b08-a8d1-e0f547a65a43',
                isActive: false,
                isColorPreview: true,
                color: '#8B88FD',
                preview: '',
                title: '',
              },
              {
                id: '6b2d1c4d-b17d-47af-bcb8-0b3b7a56e5b8',
                isActive: false,
                isColorPreview: true,
                color: '#B8EB63',
                preview: '',
                title: '',
              },
              {
                id: 'd9c1f1ed-46d2-40ff-9a6f-fb8db2a214d2',
                isActive: false,
                isColorPreview: true,
                color: '#63DBEB',
                preview: '',
                title: '',
              },
              {
                id: '1c75938c-cf5c-4e1e-93d7-1c0279c6e746',
                isActive: false,
                isColorPreview: true,
                color: '#EB6363',
                preview: '',
                title: '',
              },
              {
                id: 'cc23cb6b-28a6-4b39-b2e4-b09ed6466ad4',
                isActive: false,
                isColorPreview: true,
                color: '#EBBD63',
                preview: '',
                title: '',
              },
              {
                id: '53f5f05c-5b8e-4b65-91cb-24e8b6599d89',
                isActive: false,
                isColorPreview: true,
                color: '#003366',
                preview: '',
                title: '',
              },
              {
                id: 'e0f3b94f-b9cc-4850-98db-50e7f8f3d6db',
                isActive: false,
                isColorPreview: true,
                color: '#808080',
                preview: '',
                title: '',
              },
              {
                id: '9f3b7f3b-9b6e-4e60-9f76-1aafc2e15f82',
                isActive: false,
                isColorPreview: true,
                color: '#F5F5DC',
                preview: '',
                title: '',
              },
              {
                id: '5f72b4f6-6b9f-4baf-bb92-7d342a8c7f47',
                isActive: false,
                isColorPreview: true,
                color: '#D5B9A0',
                preview: '',
                title: '',
              },
              {
                id: '48e6f7b2-7b92-4f7b-b979-9c1a872dd823',
                isActive: false,
                isColorPreview: true,
                color: '#6B8E23',
                preview: '',
                title: '',
              },
              {
                id: 'a29b5f1a-57b4-4a02-9d6d-2db0f2c005c3',
                isActive: false,
                isColorPreview: true,
                color: '#800000',
                preview: '',
                title: '',
              },
              {
                id: 'a4fc021f-3f26-4454-8c44-7d367d295b35',
                isActive: false,
                isColorPreview: true,
                color: '#87CEEB',
                preview: '',
                title: '',
              },
              {
                id: '2c6b5c78-c529-4d2e-8d38-c8fbd0d682cf',
                isActive: false,
                isColorPreview: true,
                color: '#FFC0CB',
                preview: '',
                title: '',
              },
              {
                id: '1d4a4e1f-9b29-41e7-9277-4c5b8f2d8b27',
                isActive: false,
                isColorPreview: true,
                color: '#2F4F4F',
                preview: '',
                title: '',
              },
              {
                id: '7d42f1b8-d9f1-4e1d-b9e5-8b0367d72a4d',
                isActive: false,
                isColorPreview: true,
                color: '#E2725B',
                preview: '',
                title: '',
              },
              {
                id: 'd08e6f3b-9e4e-4299-b64d-21edb13b6f83',
                isActive: false,
                isColorPreview: true,
                color: '#98FF98',
                preview: '',
                title: '',
              },
              {
                id: '3cfc2d77-bf5e-4bfb-a1b4-929d5d26f3f2',
                isActive: false,
                isColorPreview: true,
                color: '#00FFFF',
                preview: '',
                title: '',
              },
              {
                id: '6f8b3c2d-9d24-45a4-a5ef-56d30c83b7da',
                isActive: false,
                isColorPreview: true,
                color: '#F4A460',
                preview: '',
                title: '',
              },
              {
                id: 'cb5fbb6d-549e-4c42-bdf9-754d5b2f6b3a',
                isActive: false,
                isColorPreview: true,
                color: '#4B2E2A',
                preview: '',
                title: '',
              },
              {
                id: '3a8e7a6f-bc45-4c62-b8d7-b6d5f7399ae5',
                isActive: false,
                isColorPreview: true,
                color: '#800080',
                preview: '',
                title: '',
              },
              {
                id: 'a5c8d6d8-2d8e-43a2-8b9e-bf9e0c3d1ef4',
                isActive: false,
                isColorPreview: true,
                color: '#006400',
                preview: '',
                title: '',
              },
              {
                id: 'd2f5b2f0-5274-4b7a-a052-36e542b8a2d4',
                isActive: false,
                isColorPreview: true,
                color: '#E0115F',
                preview: '',
                title: '',
              },
            ]
          }
        ]
      },
      {
        openedByDefault: false,
        categoryName: 'Inner Material',
        materialType: 'MESHSTANDARDMATERIAL',
        decals: [],
        materialNames: ['Circle021', "Circle024"],
        subCategories: [
          // {
          //   title: 'Material',
          //   options: [
          //     {
          //       id: '632b2e27-020d-47f6-b2bb-4a6c4eb30c7a',
          //       isActive: false,
          //       isColorPreview: false,
          //       color: '',
          //       preview: '/materials/leather/lather.png',
          //       title: 'leather',
          //       setting: {
          //         // roughness: "0.5",
          //         normalMap: "/materials/leather/leather_Normal_flip.jpg",
          //         roughnessMap: "/materials/leather/leather_Roughness_flip.jpg",
          //       }
          //     },
          //     {
          //       id: '00297ff1-61b4-41e4-b511-8e0f849c8d90',
          //       isActive: false,
          //       isColorPreview: false,
          //       color: '',
          //       preview: '/materials/fabric/fabric_1.png',
          //       title: 'Fabric',
          //       setting: {
          //         roughness: 0.65,
          //         normalMap: "/materials/fabric/fabric_Normal_flip.jpg",
          //         roughnessMap: "/materials/fabric/fabric_Roughness_flip.jpg",
          //       }
          //     },
          //   ]
          // },
          {
            title: 'Color',
            options: [
              {
                id: 'f0c5e22e-6f02-4b77-9448-087a3a52d788',
                isActive: false,
                isColorPreview: true,
                color: '#FFFFFF',
                preview: '',
                title: '',
              },
              {
                id: 'd5a92c62-1e8b-4f3a-8d2b-cd8a6f72b0fc',
                isActive: false,
                isColorPreview: true,
                color: '#151515',
                preview: '',
                title: '',
              },
              {
                id: '8a214b26-ff9b-4e0a-8a65-59fd0630e081',
                isActive: false,
                isColorPreview: true,
                color: '#8B88FD',
                preview: '',
                title: '',
              },
              {
                id: 'b4937b9a-b0b5-44cc-8040-319ab711dc77',
                isActive: false,
                isColorPreview: true,
                color: '#B8EB63',
                preview: '',
                title: '',
              },
              {
                id: '5a3451e6-f755-4cc0-8a42-420b45c1e847',
                isActive: false,
                isColorPreview: true,
                color: '#63DBEB',
                preview: '',
                title: '',
              },
              {
                id: 'd722e4f5-05d4-46c0-8d2e-7ff6a82d8b7b',
                isActive: false,
                isColorPreview: true,
                color: '#EB6363',
                preview: '',
                title: '',
              },
              {
                id: 'c8c7b2d7-912b-4e30-bd51-9467d23787f5',
                isActive: false,
                isColorPreview: true,
                color: '#EBBD63',
                preview: '',
                title: '',
              },
              {
                id: '7cbd07d0-d4d0-4f9e-9b5d-7f5d4e228b68',
                isActive: false,
                isColorPreview: true,
                color: '#003366',
                preview: '',
                title: '',
              },
              {
                id: '4d7c88a2-76d4-411a-8b77-e564ecb82b95',
                isActive: false,
                isColorPreview: true,
                color: '#808080',
                preview: '',
                title: '',
              },
              {
                id: 'e528c3d6-6f8f-4850-99d6-7ecfe3d85569',
                isActive: false,
                isColorPreview: true,
                color: '#F5F5DC',
                preview: '',
                title: '',
              },
              {
                id: 'a6d3c22b-227d-453a-a6f8-e2b015d6277d',
                isActive: false,
                isColorPreview: true,
                color: '#D5B9A0',
                preview: '',
                title: '',
              },
              {
                id: '9d0d1d56-8c73-45c6-b8f4-bb6ad6c31b83',
                isActive: false,
                isColorPreview: true,
                color: '#6B8E23',
                preview: '',
                title: '',
              },
              {
                id: '4a8e3487-5a1d-4e7c-9e29-8c63d9a7a5e1',
                isActive: false,
                isColorPreview: true,
                color: '#800000',
                preview: '',
                title: '',
              },
              {
                id: 'f44d0db3-823a-4581-9f71-e9159ad28a98',
                isActive: false,
                isColorPreview: true,
                color: '#87CEEB',
                preview: '',
                title: '',
              },
              {
                id: 'ca64f3d0-167a-41b2-9390-7b8ff7270e66',
                isActive: false,
                isColorPreview: true,
                color: '#FFC0CB',
                preview: '',
                title: '',
              },
              {
                id: '3d63c1b7-f4f6-49cf-92cb-3f13e8e5e3e7',
                isActive: false,
                isColorPreview: true,
                color: '#2F4F4F',
                preview: '',
                title: '',
              },
              {
                id: 'b0ef9a80-f504-4d5e-b084-b31a462d1c04',
                isActive: false,
                isColorPreview: true,
                color: '#E2725B',
                preview: '',
                title: '',
              },
              {
                id: '0c3027a6-1e69-48f4-9d56-852a027e8edc',
                isActive: false,
                isColorPreview: true,
                color: '#98FF98',
                preview: '',
                title: '',
              },
              {
                id: '1ebc8a08-3fa8-4b4d-94c8-d279a76e8f02',
                isActive: false,
                isColorPreview: true,
                color: '#00FFFF',
                preview: '',
                title: '',
              },
              {
                id: 'e4288e02-3427-4f75-8d0a-f8a8a5190a07',
                isActive: false,
                isColorPreview: true,
                color: '#F4A460',
                preview: '',
                title: '',
              },
              {
                id: 'f1e17e6d-c93f-4977-aaa1-8a0cf57562e3',
                isActive: false,
                isColorPreview: true,
                color: '#4B2E2A',
                preview: '',
                title: '',
              },
              {
                id: 'ac4a8e91-5c90-4ffb-bd39-2c6a9d2817e7',
                isActive: false,
                isColorPreview: true,
                color: '#800080',
                preview: '',
                title: '',
              },
              {
                id: 'f95a88f0-8b08-4a7f-bb61-8a1dfc944c5c',
                isActive: false,
                isColorPreview: true,
                color: '#006400',
                preview: '',
                title: '',
              },
              {
                id: 'd077cf45-1e53-41e2-8418-2c5cfd7d5f7c',
                isActive: false,
                isColorPreview: true,
                color: '#E0115F',
                preview: '',
                title: '',
              },
            ]
          }
        ]
      },
    ]
  }
};
